# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hcy/QT_pro/smart-cycling-computer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hcy/QT_pro/smart-cycling-computer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hcy/QT_pro/smart-cycling-computer/CMakeFiles /home/hcy/QT_pro/smart-cycling-computer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hcy/QT_pro/smart-cycling-computer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named scc-app

# Build rule for target.
scc-app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scc-app
.PHONY : scc-app

# fast build rule for target.
scc-app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scc-app.dir/build.make CMakeFiles/scc-app.dir/build
.PHONY : scc-app/fast

#=============================================================================
# Target rules for targets named scc-app_qmlimportscan

# Build rule for target.
scc-app_qmlimportscan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scc-app_qmlimportscan
.PHONY : scc-app_qmlimportscan

# fast build rule for target.
scc-app_qmlimportscan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scc-app_qmlimportscan.dir/build.make CMakeFiles/scc-app_qmlimportscan.dir/build
.PHONY : scc-app_qmlimportscan/fast

#=============================================================================
# Target rules for targets named scc-app_autogen

# Build rule for target.
scc-app_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scc-app_autogen
.PHONY : scc-app_autogen

# fast build rule for target.
scc-app_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scc-app_autogen.dir/build.make CMakeFiles/scc-app_autogen.dir/build
.PHONY : scc-app_autogen/fast

scc-app_autogen/EWIEGA46WW/qrc_qml.o: scc-app_autogen/EWIEGA46WW/qrc_qml.cpp.o
.PHONY : scc-app_autogen/EWIEGA46WW/qrc_qml.o

# target to build an object file
scc-app_autogen/EWIEGA46WW/qrc_qml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scc-app.dir/build.make CMakeFiles/scc-app.dir/scc-app_autogen/EWIEGA46WW/qrc_qml.cpp.o
.PHONY : scc-app_autogen/EWIEGA46WW/qrc_qml.cpp.o

scc-app_autogen/EWIEGA46WW/qrc_qml.i: scc-app_autogen/EWIEGA46WW/qrc_qml.cpp.i
.PHONY : scc-app_autogen/EWIEGA46WW/qrc_qml.i

# target to preprocess a source file
scc-app_autogen/EWIEGA46WW/qrc_qml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scc-app.dir/build.make CMakeFiles/scc-app.dir/scc-app_autogen/EWIEGA46WW/qrc_qml.cpp.i
.PHONY : scc-app_autogen/EWIEGA46WW/qrc_qml.cpp.i

scc-app_autogen/EWIEGA46WW/qrc_qml.s: scc-app_autogen/EWIEGA46WW/qrc_qml.cpp.s
.PHONY : scc-app_autogen/EWIEGA46WW/qrc_qml.s

# target to generate assembly for a file
scc-app_autogen/EWIEGA46WW/qrc_qml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scc-app.dir/build.make CMakeFiles/scc-app.dir/scc-app_autogen/EWIEGA46WW/qrc_qml.cpp.s
.PHONY : scc-app_autogen/EWIEGA46WW/qrc_qml.cpp.s

scc-app_autogen/EWIEGA46WW/qrc_res.o: scc-app_autogen/EWIEGA46WW/qrc_res.cpp.o
.PHONY : scc-app_autogen/EWIEGA46WW/qrc_res.o

# target to build an object file
scc-app_autogen/EWIEGA46WW/qrc_res.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scc-app.dir/build.make CMakeFiles/scc-app.dir/scc-app_autogen/EWIEGA46WW/qrc_res.cpp.o
.PHONY : scc-app_autogen/EWIEGA46WW/qrc_res.cpp.o

scc-app_autogen/EWIEGA46WW/qrc_res.i: scc-app_autogen/EWIEGA46WW/qrc_res.cpp.i
.PHONY : scc-app_autogen/EWIEGA46WW/qrc_res.i

# target to preprocess a source file
scc-app_autogen/EWIEGA46WW/qrc_res.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scc-app.dir/build.make CMakeFiles/scc-app.dir/scc-app_autogen/EWIEGA46WW/qrc_res.cpp.i
.PHONY : scc-app_autogen/EWIEGA46WW/qrc_res.cpp.i

scc-app_autogen/EWIEGA46WW/qrc_res.s: scc-app_autogen/EWIEGA46WW/qrc_res.cpp.s
.PHONY : scc-app_autogen/EWIEGA46WW/qrc_res.s

# target to generate assembly for a file
scc-app_autogen/EWIEGA46WW/qrc_res.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scc-app.dir/build.make CMakeFiles/scc-app.dir/scc-app_autogen/EWIEGA46WW/qrc_res.cpp.s
.PHONY : scc-app_autogen/EWIEGA46WW/qrc_res.cpp.s

scc-app_autogen/mocs_compilation.o: scc-app_autogen/mocs_compilation.cpp.o
.PHONY : scc-app_autogen/mocs_compilation.o

# target to build an object file
scc-app_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scc-app.dir/build.make CMakeFiles/scc-app.dir/scc-app_autogen/mocs_compilation.cpp.o
.PHONY : scc-app_autogen/mocs_compilation.cpp.o

scc-app_autogen/mocs_compilation.i: scc-app_autogen/mocs_compilation.cpp.i
.PHONY : scc-app_autogen/mocs_compilation.i

# target to preprocess a source file
scc-app_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scc-app.dir/build.make CMakeFiles/scc-app.dir/scc-app_autogen/mocs_compilation.cpp.i
.PHONY : scc-app_autogen/mocs_compilation.cpp.i

scc-app_autogen/mocs_compilation.s: scc-app_autogen/mocs_compilation.cpp.s
.PHONY : scc-app_autogen/mocs_compilation.s

# target to generate assembly for a file
scc-app_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scc-app.dir/build.make CMakeFiles/scc-app.dir/scc-app_autogen/mocs_compilation.cpp.s
.PHONY : scc-app_autogen/mocs_compilation.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scc-app.dir/build.make CMakeFiles/scc-app.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scc-app.dir/build.make CMakeFiles/scc-app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scc-app.dir/build.make CMakeFiles/scc-app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... scc-app_autogen"
	@echo "... scc-app_qmlimportscan"
	@echo "... scc-app"
	@echo "... scc-app_autogen/EWIEGA46WW/qrc_qml.o"
	@echo "... scc-app_autogen/EWIEGA46WW/qrc_qml.i"
	@echo "... scc-app_autogen/EWIEGA46WW/qrc_qml.s"
	@echo "... scc-app_autogen/EWIEGA46WW/qrc_res.o"
	@echo "... scc-app_autogen/EWIEGA46WW/qrc_res.i"
	@echo "... scc-app_autogen/EWIEGA46WW/qrc_res.s"
	@echo "... scc-app_autogen/mocs_compilation.o"
	@echo "... scc-app_autogen/mocs_compilation.i"
	@echo "... scc-app_autogen/mocs_compilation.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

